{{- if .Values.credentials.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "webhook.labels" . | nindent 4 }}
type: Opaque
stringData:
  apiUser: {{ .Values.credentials.apiUser | quote }}
  apiKey: {{ .Values.credentials.apiKey | quote }}
  username: {{ .Values.credentials.username | default .Values.credentials.apiUser | quote }}
  clientIP: {{ .Values.credentials.clientIP | quote }}
{{- end }}
